# Generated by Django 4.1.2 on 2022-10-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201101_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True,
                                         related_name='courses',
                                         to='students.student'),
        ),
    ]
